
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 16 09:28:30 CST 2017
//----------------------------------------------------

package pascalcompiler;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int PMENOS = 34;
  public static final int PDO = 23;
  public static final int PAND = 50;
  public static final int PMENOR = 41;
  public static final int PBREAK = 72;
  public static final int PWORD = 10;
  public static final int PENTERO = 95;
  public static final int PINT64 = 8;
  public static final int PXOR = 47;
  public static final int PWRITELN = 78;
  public static final int PRECORD = 67;
  public static final int PSHORTINT = 5;
  public static final int PORELSE = 26;
  public static final int PLABEL = 73;
  public static final int PMOD2 = 38;
  public static final int PENTRE = 36;
  public static final int PMENORIGUAL = 43;
  public static final int PDOWNTO = 69;
  public static final int PIN = 84;
  public static final int PCOMENTARIOC = 57;
  public static final int POR = 49;
  public static final int PSUBRANGE = 89;
  public static final int PPUNTOCOMA = 55;
  public static final int PCOMENTARIOA = 56;
  public static final int PFUNCTION = 65;
  public static final int PTHEN = 20;
  public static final int PGOTO = 70;
  public static final int PPROGRAM = 61;
  public static final int PIF = 19;
  public static final int PID = 93;
  public static final int POF = 85;
  public static final int PRETURN = 71;
  public static final int PREADLN = 79;
  public static final int PPARC = 54;
  public static final int PPARA = 53;
  public static final int PPOR = 35;
  public static final int PBEGIN = 62;
  public static final int PCONTINUE = 68;
  public static final int PCOMA = 77;
  public static final int PPOINTER = 75;
  public static final int PSHR = 91;
  public static final int PNOT = 48;
  public static final int PTRUE = 58;
  public static final int PNIL = 60;
  public static final int PSHL = 90;
  public static final int PVAR = 83;
  public static final int PFLOTANTE = 96;
  public static final int PREPEAT = 28;
  public static final int PCHAR = 18;
  public static final int PTO = 29;
  public static final int PENUMERATED = 14;
  public static final int PANDTHEN = 31;
  public static final int PMAYORIGUAL = 44;
  public static final int PMOD = 37;
  public static final int PELSE = 21;
  public static final int PCONST = 80;
  public static final int PINTEGER = 17;
  public static final int PUNTIL = 27;
  public static final int PMAYOR = 42;
  public static final int PTEXTO = 97;
  public static final int PCOMPARE = 40;
  public static final int PCARDINAL = 3;
  public static final int PSTRING = 15;
  public static final int EOF = 0;
  public static final int PFOR = 22;
  public static final int PDIV = 81;
  public static final int PBITWISER = 46;
  public static final int PMAS = 33;
  public static final int PBITWISEL = 45;
  public static final int PDISTINTO = 39;
  public static final int PFALSE = 59;
  public static final int PLONGWORD = 11;
  public static final int error = 1;
  public static final int PARRAY = 2;
  public static final int PERROR = 98;
  public static final int PFILE = 82;
  public static final int PPACKED = 86;
  public static final int PCHARACTER = 12;
  public static final int PDESDEHASTA = 76;
  public static final int PASIG = 32;
  public static final int PCASE = 25;
  public static final int PSET = 87;
  public static final int PBOOLEAN = 16;
  public static final int PBYTE = 9;
  public static final int PDOUBLE = 4;
  public static final int PCLASS = 64;
  public static final int PLONGINT = 7;
  public static final int PPROCEDURE = 66;
  public static final int PWITH = 30;
  public static final int PDOSPUNTOS = 74;
  public static final int PEND = 63;
  public static final int PWHILE = 24;
  public static final int PSMALLINT = 6;
  public static final int PREAL = 13;
  public static final int PBRACKETC = 52;
  public static final int PBRACKETA = 51;
  public static final int PNUMERO = 94;
  public static final int PTYPE = 88;
  public static final int PNEW = 92;
}

